### ISSUE TITLE
不支持.NET6吗？.NET6中App.cs中无法继承ApplicationBase

### ISSUE THREAD

**Issue by XiaoYongV5** [HeBianGu/WPF-ControlBase#6]
项目版本为.NET6，按照Demo4中的写法，引入了以下三个依赖包 
using HeBianGu.Base.WpfBase;
using HeBianGu.Control.ThemeSet;
using HeBianGu.General.WpfControlLib;

存在两个问题，代码无法通过编译
1. 无法继承 ApplicationBase ，异常提示：“APP”分部声明一定不能指定不同的基类
2. 无法注册消息AddMessage，提示未包含此定义

**Comment by HeBianGu** [comment]
目前最高支持.net5，后面版本会升级更高版本
