### ISSUE TITLE
请问框架有实现ViewModel之间数据传递的功能吗？

### ISSUE THREAD

**Issue by Anonymy** [HeBianGu/WPF-ControlBase#7]
#我在框架中暂未找到ViewModel之间数据传递的实现方式，请问作者有实现这块内容吗？类似于Prism中的时间聚合器，如果框架暂未实现，基于现有框架您推荐使用什么方式实现ViewModel之间的数据传递。谢谢！

**Comment by HeBianGu** [comment]
事件聚合器目前没有，我这边目前尽量是把ViewModel通过MVC的方式隔离开，一般不需要交互，对于数据交互方面通过单独定义Domain或者Service层，再或者通过数据库仓储和DBContext交互，特殊情况下ViewModel交互是用IOC注入的方式交互，比如你可以在代码中搜索下DataSourceLocator参考这种方式ServiceRegistry.Instance.GetInstance<ShellViewModel>()

**Comment by Anonymy** [comment]
谢谢！
